### ISSUE TITLE
webpack failed with cloudbuild

### ISSUE THREAD

**Issue by avinashdubeyse** [ankita1010/create-webpack-react-app#4]
Hi
I tried this package and its failed when I am trying to build with Cloudbuild with CloudRun

**Error log**
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 2
ERROR
Finished Step #0
Step #0: The command '/bin/sh -c yarn build' returned a non-zero code: 2
Step #0: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Step #0: error Command failed with exit code 2.
Step #0:     [0] ./node_modules/html-webpack-plugin/lib/loader.js!./public/index.html 594 bytes {0} [built]
Step #0:     Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
Step #0:      1 asset
Step #0: Child HtmlWebpackCompiler:
Step #0:  @ multi @babel/polyfill ./src/index.js bundle[1]
Step #0:     at step (/app/node_modules/gensync/index.js:254:32)
Step #0:     at transform.next (<anonymous>)
Step #0:     at Function.transform (/app/node_modules/@babel/core/lib/transform.js:27:41)
Step #0:     at run.next (<anonymous>)
Step #0:     at run (/app/node_modules/@babel/core/lib/transformation/index.js:31:50)
Step #0:     at normalizeFile.next (<anonymous>)
Step #0:     at normalizeFile (/app/node_modules/@babel/core/lib/transformation/normalize-file.js:93:38)
Step #0:     at parser.next (<anonymous>)
Step #0:     at parser (/app/node_modules/@babel/core/lib/parser/index.js:54:34)
Step #0:     at parse (/app/node_modules/@babel/parser/lib/index.js:12722:38)
Step #0:     at Parser.parse (/app/node_modules/@babel/parser/lib/index.js:12671:10)
Step #0:     at Parser.parseTopLevel (/app/node_modules/@babel/parser/lib/index.js:11035:10)
Step #0:     at Parser.parseBlockBody (/app/node_modules/@babel/parser/lib/index.js:11665:10)
Step #0:     at Parser.parseBlockOrModuleBlockBody (/app/node_modules/@babel/parser/lib/index.js:11679:25)
Step #0:     at Parser.parseStatement (/app/node_modules/@babel/parser/lib/index.js:11104:17)
Step #0:     at Parser.parseStatementContent (/app/node_modules/@babel/parser/lib/index.js:11233:23)
Step #0:     at Parser.parseExpression (/app/node_modules/@babel/parser/lib/index.js:9354:23)
Step #0:     at Parser.parseMaybeAssign (/app/node_modules/@babel/parser/lib/index.js:9402:21)
Step #0:     at Parser.parseMaybeConditional (/app/node_modules/@babel/parser/lib/index.js:9447:23)
Step #0:     at Parser.parseExprOps (/app/node_modules/@babel/parser/lib/index.js:9474:23)
Step #0:     at Parser.parseMaybeUnary (/app/node_modules/@babel/parser/lib/index.js:9604:21)
Step #0:     at Parser.parseExprSubscripts (/app/node_modules/@babel/parser/lib/index.js:9630:17)
Step #0:     at Parser.parseSubscripts (/app/node_modules/@babel/parser/lib/index.js:9647:19)
Step #0:     at Parser.parseSubscript (/app/node_modules/@babel/parser/lib/index.js:9718:31)
Step #0:     at Parser.parseCallExpressionArguments (/app/node_modules/@babel/parser/lib/index.js:9812:22)
Step #0:     at Parser.parseExprListItem (/app/node_modules/@babel/parser/lib/index.js:10740:18)
Step #0:     at Parser.parseMaybeAssign (/app/node_modules/@babel/parser/lib/index.js:9402:21)
Step #0:     at Parser.parseMaybeConditional (/app/node_modules/@babel/parser/lib/index.js:9447:23)
Step #0:     at Parser.parseExprOps (/app/node_modules/@babel/parser/lib/index.js:9474:23)
Step #0:     at Parser.parseMaybeUnary (/app/node_modules/@babel/parser/lib/index.js:9604:21)
Step #0:     at Parser.parseExprSubscripts (/app/node_modules/@babel/parser/lib/index.js:9624:23)
Step #0:     at Parser.parseExprAtom (/app/node_modules/@babel/parser/lib/index.js:10074:20)
Step #0:     at Parser.unexpected (/app/node_modules/@babel/parser/lib/index.js:8779:16)
Step #0:     at Parser.raise (/app/node_modules/@babel/parser/lib/index.js:729:17)
Step #0:     at Parser.raiseWithData (/app/node_modules/@babel/parser/lib/index.js:735:17)
Step #0:     at Parser._raise (/app/node_modules/@babel/parser/lib/index.js:742:17)
Step #0:   9 | 		
Step #0:   8 | );
**Step #0:   7 |     document.getElementById('root')
Step #0:     |         ^
Step #0: > 6 |         <App/>,
Step #0:   5 | ReactDOM.render(**
Step #0:   4 | 
Step #0: 
Step #0: SyntaxError: /app/src/index.js: Unexpected token (6:8)
Step #0: Module build failed (from ./node_modules/babel-loader/lib/index.js):
Step #0: ERROR in ./src/index.js
Step #0:

**Comment by ankita1010** [comment]
Hi, there seems to be a syntax error in index.js (unexpected token) as suggested by the build log. Could you try solving that?
